version: "3.5"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com.br'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com.br'
    ports:
      - '80:80'
      - '443:443'
      - '23:22'
    volumes:
      - './configs/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/gitlab/data:/var/opt/gitlab'

  redis:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    depends_on:
      - web
    volumes:
      - './configs/redis/config:/etc/gitlab'
      - '/srv/gitlab/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/gitlab/data:/var/opt/gitlab'    